
--Si besoin de détruire les tables & les contraintes & les séquences.
DROP TABLE REPONSE ON CASCADE CONSTRAINTS;
DROP TABLE MESSAGE_MUR ON CASCADE CONSTRAINTS;
DROP TABLE AMI ON CASCADE CONSTRAINTS;
DROP TABLE UTILISATEUR ON CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MESSAGE;
DROP SEQUENCE SEQ_REPONSE;

-- Table des Utilisateurs
CREATE TABLE UTILISATEUR (
    LOGIN VARCHAR2(50) PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    MDP VARCHAR2(100) NOT NULL,
    DATE_CREATION DATE DEFAULT SYSDATE
);

-- Table des Amis
CREATE TABLE AMI (
    LOGIN_UTILISATEUR1 VARCHAR2(50) REFERENCES UTILISATEUR(LOGIN),
    LOGIN_UTILISATEUR2 VARCHAR2(50) REFERENCES UTILISATEUR(LOGIN),
    DATE_AMITIE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_AMI PRIMARY KEY (LOGIN_UTILISATEUR1, LOGIN_UTILISATEUR2),
    CONSTRAINT CK_AMI_ORDRE CHECK (LOGIN_UTILISATEUR1 < LOGIN_UTILISATEUR2)
);

-- Table des Messages sur le Mur
CREATE TABLE MESSAGE_MUR (
    ID_MESSAGE          NUMBER        PRIMARY KEY,
    LOGIN_PROPRIETAIRE  VARCHAR2(50)  REFERENCES UTILISATEUR(LOGIN) NOT NULL,
    LOGIN_AUTEUR        VARCHAR2(50)  REFERENCES UTILISATEUR(LOGIN) NOT NULL,
    CONTENU             VARCHAR2(4000) NOT NULL,
    DATE_PUBLICATION    DATE          DEFAULT SYSDATE
);

-- Table Rep Messages
CREATE TABLE REPONSE (
    ID_REPONSE NUMBER PRIMARY KEY,
    ID_MESSAGE_PARENT NUMBER REFERENCES MESSAGE_MUR(ID_MESSAGE) ON DELETE CASCADE NOT NULL,
    LOGIN_AUTEUR VARCHAR2(50) REFERENCES UTILISATEUR(LOGIN) NOT NULL,
    CONTENU VARCHAR2(4000) NOT NULL,
    DATE_REPONSE DATE DEFAULT SYSDATE
);

-- Séquences de générations des clés
CREATE SEQUENCE SEQ_MESSAGE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPONSE START WITH 1 INCREMENT BY 1 NOCACHE;

-- Trigger pour MESSAGE_MUR
CREATE OR REPLACE TRIGGER TRG_MESSAGE_MUR_ID
BEFORE INSERT ON MESSAGE_MUR
FOR EACH ROW
BEGIN
    SELECT SEQ_MESSAGE.NEXTVAL INTO :NEW.ID_MESSAGE FROM DUAL;
END;
/

-- Trigger pour REPONSE
CREATE OR REPLACE TRIGGER TRG_REPONSE_ID
BEFORE INSERT ON REPONSE
FOR EACH ROW

BEGIN
    SELECT SEQ_REPONSE.NEXTVAL INTO :NEW.ID_REPONSE FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_MESSAGE_MUR_EVENEMENT
AFTER INSERT ON MESSAGE_MUR
FOR EACH ROW

BEGIN
    DBMS_OUTPUT.PUT_LINE('*** ÉVÉNEMENT *** : Message Mur Envoyé par ' || :NEW.LOGIN_AUTEUR || ' à ' || :NEW.LOGIN_PROPRIETAIRE || '.');
END;
/

COMMIT;